# Generated by Django 3.2.4 on 2021-07-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativoCanton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
