# Generated by Django 3.2.4 on 2021-07-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativoCanton', '0002_alter_persona_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
